### ISSUE TITLE
Question: How can I install orapass so it integrates with the sqlplus cli?

### ISSUE THREAD

**Issue by emeraldjava** [gsiems/orapass#1]
Hi,
I've a two fold question
1. Do i need to update the PATH details of my system so the orapass go application can be executed?
2. Does the orapass integrate with sqlplus cli. If i understand the process correctly, i should be able to give sqlplus the DB connection string, and if the orapass file exists and has the password - i won't be promted for a db credential. 
Thanks,
Paul

**Comment by gsiems** [comment]
I've added an example osql.sh bash script to the repo. If you are running an OS that has bash then this should work.

**Comment by emeraldjava** [comment]
Thanks, it's a wrapper script which calls orapass on the way and then invokes the sql client with the generated url. Neat.
